# k8s/overlays/green/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
resources:
- ../../base

namePrefix: green-

# Common labels for all resources in this overlay
labels:
- includeSelectors: true
  pairs:
    environment: green
    version: green

# Patches for the green deployment
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
- path: ingress-canary-patch.yaml
- path: ingress-patch.yaml
- path: namespace-patch.yaml