# k8s/overlays/green/service-patch.yaml
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app
  labels:
    app: todo-app
spec:
  selector:
    # These labels must match the labels on the Pods created by the 'green-todo-app' Deployment.
    app: todo-app
    environment: green # This label is added by the green overlay's kustomization.yaml