# k8s/overlays/blue/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Inherit from the base configuration
resources:
- ../../base

namePrefix: blue-

# Common labels for all resources in this overlay
labels:
- includeSelectors: true
  pairs:
    environment: blue
    version: blue
    
# Patches for the blue deployment
patches:
- path: deployment-patch.yaml
- path: service-patch.yaml
