# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Specifies the namespace for all resources in this kustomization.
# This can be overridden by overlays if needed, or by the root kustomization if it were active.
namespace: todo-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-canary.yaml

secretGenerator:
  - name: todo-app-secret
    envs:
      - secrets.env

configMapGenerator:
  - name: todo-app-config
    envs:
      - configs.env

# Common labels for base resources. These can be augmented by overlays.
commonLabels:
  app.kubernetes.io/name: todo-app
  app.kubernetes.io/instance: todo-app-instance # This is used by service selectors
  app.kubernetes.io/component: application
  app.kubernetes.io/part-of: todo-application
  app.kubernetes.io/managed-by: kustomize

# Base image configuration. Overlays or CI/CD can change this.
images:
  - name: your-dockerhub-username/todo-app # Default image name in deployment.yaml
    newName: your-dockerhub-username/todo-app # Can be overridden
    newTag: base # Default tag for base, can be overridden