# k8s/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Specifies the namespace for all resources in this kustomization.
# This can be overridden by overlays if needed, or by the root kustomization if it were active.
namespace: todo-app

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- ingress-canary.yaml

secretGenerator:
- envs:
  - secrets.env
  name: todo-app-secret

configMapGenerator:
- envs:
  - configs.env
  name: todo-app-config

# Common labels for base resources. These can be augmented by overlays.

# Base image configuration. Overlays or CI/CD can change this.
images:
- name: your-dockerhub-username/todo-app
  newName: your-dockerhub-username/todo-app
  newTag: base
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: application
    app.kubernetes.io/instance: todo-app-instance
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: todo-app
    app.kubernetes.io/part-of: todo-application
